---
title: "tidy_data"
author: "Yuxuan Chen"
date: "9/30/2021"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_df
```

Let's try pivot
```{r}
pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>%
  mutate(
    visit = replace(visit == "bi", "00m")
    )
```

```{r}
analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4,8,3,6)
  )

analysis_df %>%
  pivot_wider(
    names_from = "time",
    value_from = "group mean"
  )
```


## bind_rows
import the LotR movie words stuff

```{r}
fellowship_df = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:B6") %>%
  mutate(movie = "fellowship_rings")

two_towers_df = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_df = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_df) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>%
  relocate(movie)

```

 - never use `rbinds()`, always use `bind_row()`.
 - never use `gather()`, always use `pivot_longer()`
 - never use `spread()`, always use `pivot_wider()`


## joins

Look at FAS data.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), 3) %>%
  relocate(litter_number)  %>% 
  mutate(dose = str_to_lower(dose))


 pups_df = 
  read_csv("data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, '1' = "male", '2' = "female")) 
        #'1' is a variable but not number, forcing R to recognize
   
```


Let's join these up!
```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  relocate(litter_number, dose, day_of_tx)

```

